name: Generate static binaries
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
jobs:
  learn-ocaml-www-zip:
    name: Build learn-ocaml-www.zip archive
    if: ${{ github.event_name != 'schedule' || github.repository == 'pfitaxel/learn-ocaml-issue475-poc' }}
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.export.outputs.artifact }}
    strategy:
      matrix:
        arch_dir: ["learn-ocaml-www"]
        # we could use an env var, albeit it would be less convenient
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: 'Build ${{ matrix.arch_dir }}.zip'
        run: |
          url="https://ocaml-sf.org/learn-ocaml/"
          mkdir "${{ matrix.arch_dir }}"
          sed -e "s|{{url}}|$url|g" index.html.mustache >"${{ matrix.arch_dir }}/index.html"
          zip -r "${{ matrix.arch_dir }}.zip" "${{ matrix.arch_dir }}"
      - name: 'Upload ${{ matrix.arch_dir }}.zip'
        uses: actions/upload-artifact@v2
        with:
          name: '${{ matrix.arch_dir }}.zip'
          path: '${{ matrix.arch_dir }}.zip'
      - id: export
        name: Export artifact filename
        run: echo "artifact=${{ matrix.arch_dir }}.zip" >> $GITHUB_OUTPUT
        # this last step is not necessary
